[platformio]
default_envs = remus-proto1
src_dir = platforms/esp32/src
include_dir = platforms/esp32/include

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I lib/remus-core/include

[env:remus-proto1]
extra_scripts = platforms/esp32/download_sd.py
build_flags =
    ${env.build_flags}
    -D REMUS_TARGET_FULL=1
    -D REMUS_PROFILE_PROTO1=1
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    moononournation/GFX Library for Arduino @ 1.5.5
build_src_filter =
    +<*>
    -<app/BladeApp.cpp>

[env:remus-blade-dev]
build_flags =
    ${env.build_flags}
    -D REMUS_TARGET_BLADE=1
    -D REMUS_PROFILE_BLADE_DEV=1
build_src_filter =
    +<main.cpp>
    +<app/BladeApp.cpp>
    +<drivers/Mpu6050Imu.cpp>
